version: "3.9"

services:
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - redis
      - db
    networks: [vacasnet]

  celery:
    build: ./backend
    command: celery -A tasks worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - backend
    networks: [vacasnet]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks: [vacasnet]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vacas
    ports:
      - "5432:5432"
    networks: [vacasnet]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks: [vacasnet]

networks:
  vacasnet:
    driver: bridge
