export const APP_CONFIG = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  API_KEY: import.meta.env.VITE_API_KEY,
  DEFAULT_LANGUAGE: "en",
  DATE_FORMAT: "YYYY-MM-DD",
  DEFAULT_PAGE_SIZE: 10,
  EMAIL_LENGTH: 255,
  EMAIL_DOMAIN: "@",
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 100,
};
